"""Add analytics tables

Revision ID: 0009_add_analytics_tables
Revises: 0008_backfill_global_decks_default_org
Create Date: 2026-03-23 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0009_add_analytics_tables'
down_revision = '0008_backfill_global_decks_default_org'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_analytics',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_reviews', sa.Integer(), nullable=False),
    sa.Column('correct_reviews', sa.Integer(), nullable=False),
    sa.Column('accuracy_rate', sa.Float(), nullable=False),
    sa.Column('total_study_time_minutes', sa.Integer(), nullable=False),
    sa.Column('average_session_minutes', sa.Float(), nullable=False),
    sa.Column('study_streak_days', sa.Integer(), nullable=False),
    sa.Column('decks_studied', sa.Integer(), nullable=False),
    sa.Column('cards_studied', sa.Integer(), nullable=False),
    sa.Column('new_cards_learned', sa.Integer(), nullable=False),
    sa.Column('tests_taken', sa.Integer(), nullable=False),
    sa.Column('average_test_score', sa.Float(), nullable=False),
    sa.Column('ai_generated_cards_studied', sa.Integer(), nullable=False),
    sa.Column('mcqs_practiced', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_analytics_period_end'), 'user_analytics', ['period_end'], unique=False)
    op.create_index(op.f('ix_user_analytics_period_start'), 'user_analytics', ['period_start'], unique=False)
    op.create_index(op.f('ix_user_analytics_user_id'), 'user_analytics', ['user_id'], unique=False)
    op.create_table('organization_analytics',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_users', sa.Integer(), nullable=False),
    sa.Column('active_users', sa.Integer(), nullable=False),
    sa.Column('total_reviews', sa.Integer(), nullable=False),
    sa.Column('correct_reviews', sa.Integer(), nullable=False),
    sa.Column('organization_accuracy_rate', sa.Float(), nullable=False),
    sa.Column('total_study_time_minutes', sa.Integer(), nullable=False),
    sa.Column('average_study_time_per_user', sa.Float(), nullable=False),
    sa.Column('total_decks', sa.Integer(), nullable=False),
    sa.Column('total_cards', sa.Integer(), nullable=False),
    sa.Column('decks_studied', sa.Integer(), nullable=False),
    sa.Column('tests_taken', sa.Integer(), nullable=False),
    sa.Column('average_test_score', sa.Float(), nullable=False),
    sa.Column('ai_generated_content_used', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_analytics_period_end'), 'organization_analytics', ['period_end'], unique=False)
    op.create_index(op.f('ix_organization_analytics_period_start'), 'organization_analytics', ['period_start'], unique=False)
    op.create_index(op.f('ix_organization_analytics_organization_id'), 'organization_analytics', ['organization_id'], unique=False)
    op.create_table('system_analytics',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_organizations', sa.Integer(), nullable=False),
    sa.Column('total_users', sa.Integer(), nullable=False),
    sa.Column('active_users', sa.Integer(), nullable=False),
    sa.Column('system_admins', sa.Integer(), nullable=False),
    sa.Column('total_reviews', sa.Integer(), nullable=False),
    sa.Column('correct_reviews', sa.Integer(), nullable=False),
    sa.Column('system_accuracy_rate', sa.Float(), nullable=False),
    sa.Column('total_study_time_minutes', sa.Integer(), nullable=False),
    sa.Column('average_study_time_per_user', sa.Float(), nullable=False),
    sa.Column('total_decks', sa.Integer(), nullable=False),
    sa.Column('total_cards', sa.Integer(), nullable=False),
    sa.Column('total_ai_generated_cards', sa.Integer(), nullable=False),
    sa.Column('total_mcqs_generated', sa.Integer(), nullable=False),
    sa.Column('tests_taken', sa.Integer(), nullable=False),
    sa.Column('average_test_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_analytics_period_end'), 'system_analytics', ['period_end'], unique=False)
    op.create_index(op.f('ix_system_analytics_period_start'), 'system_analytics', ['period_start'], unique=False)
    op.create_table('analytics_events',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('event_type', sa.Enum('review_completed', 'test_started', 'test_completed', 'deck_created', 'card_created', 'ai_upload_processed', 'mcq_generated', 'tag_assigned', name='analyticseventtype'), nullable=False),
    sa.Column('event_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_data', sa.Text(), nullable=True),
    sa.Column('source_ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_events_event_timestamp'), 'analytics_events', ['event_timestamp'], unique=False)
    op.create_index(op.f('ix_analytics_events_event_type'), 'analytics_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_analytics_events_organization_id'), 'analytics_events', ['organization_id'], unique=False)
    op.create_index(op.f('ix_analytics_events_user_id'), 'analytics_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analytics_events_user_id'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_organization_id'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_event_type'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_event_timestamp'), table_name='analytics_events')
    op.drop_table('analytics_events')
    op.drop_index(op.f('ix_system_analytics_period_start'), table_name='system_analytics')
    op.drop_index(op.f('ix_system_analytics_period_end'), table_name='system_analytics')
    op.drop_table('system_analytics')
    op.drop_index(op.f('ix_organization_analytics_organization_id'), table_name='organization_analytics')
    op.drop_index(op.f('ix_organization_analytics_period_start'), table_name='organization_analytics')
    op.drop_index(op.f('ix_organization_analytics_period_end'), table_name='organization_analytics')
    op.drop_table('organization_analytics')
    op.drop_index(op.f('ix_user_analytics_user_id'), table_name='user_analytics')
    op.drop_index(op.f('ix_user_analytics_period_start'), table_name='user_analytics')
    op.drop_index(op.f('ix_user_analytics_period_end'), table_name='user_analytics')
    op.drop_table('user_analytics')
    # ### end Alembic commands ###